### ISSUE TITLE
Preferred citation

### ISSUE THREAD

**Issue by kijinosu** [unt-libraries/pynaco#16]
I want to cite this repository in a paper. What is your preferred citation?

**Comment by ldko** [comment]
Hi @kijinosu . Thanks for getting in touch. @vphill has added a .cff file, so you can now get a citation on the home page of the repo via About->Cite this repository. Currently it appears as:
```
University of North Texas Libraries. (2021). pynaco (Version 1.0.0) [Computer software]. https://github.com/unt-libraries/pynaco
```

**Comment by kijinosu** [comment]
Thank you.
