### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by damonkelley** [unt-libraries/pynaco#5]
We need to make `naco.py` compatible with Python 3 (because it is 2015 and other good reasons). At the moment, I am unsure what all needs to be changed.

 One thing I am certain of though, is that `UnicodeType` does not exist in the `types` module in Python 3. 

Adding this compatibility will be easier if/when tox is integrated in to the testing strategy.

**Comment by damonkelley** [comment]
>One thing I am certain of though, is that UnicodeType does not exist in the types module in Python 3. 

 https://github.com/unt-libraries/pynaco/blob/master/pynaco/naco.py#L2

**Comment by vphill** [comment]
Finally getting this upgraded #12
